Repository UNLV-CS472-672/2024-S-GROUP3-Barbell, pull requests merged in 2024-03, with the labels that each got.

#126 126 backend prisma api for spotify data
  packages/api/src/root.ts
  packages/api/src/router/spotify.ts
Labels: help wanted, backend

#137 Frontend -- Added styling to MessageView in index.tsx.
  apps/expo/src/app/messages/index.tsx
  apps/expo/src/components/notif/dmNotifs/Conversation.tsx
  apps/expo/src/context/global-context.tsx
Labels: frontend

#116 43 frontend profile screen structure
  README.md
  apps/expo/src/app/[...unmatched].tsx
  apps/expo/src/app/contact-us.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/privacy-policy.tsx
  apps/expo/src/app/user/achievements.tsx
  apps/expo/src/app/user/activity-history.tsx
  apps/expo/src/app/user/index.tsx
  apps/expo/src/app/user/personal-data.tsx
  apps/expo/src/app/user/workout-progress.tsx
Labels: enhancement, frontend

#141 138 backend create api endpoint for friends
  apps/nextjs/src/app/_components/users.tsx
  packages/api/src/root.ts
  packages/api/src/router/friend.ts
Labels: backend

#143 142 cicd code coverage right here
  .github/workflows/cov.yml
  codecov.yml
  requirements.txt
Labels: enhancement, build

#134 30 frontend bottom nav
  .github/general_issue.md
  README.md
  app.json
  apps/expo/assets/fonts/IstokWeb.ttf
  apps/expo/assets/fonts/Sora.ttf
  apps/expo/assets/icon.png
  apps/expo/assets/svgs/circle-minus.svg
  apps/expo/assets/svgs/circle-plus.svg
  apps/expo/assets/svgs/home.svg
  apps/expo/assets/svgs/profile.svg
  apps/expo/babel.config.js
  apps/expo/eas.json
  apps/expo/metro.config.js
  apps/expo/package.json
  apps/expo/src/app/(tabs)/_layout.tsx
  apps/expo/src/app/(tabs)/index.tsx
  apps/expo/src/app/(tabs)/one.tsx
  apps/expo/src/app/(tabs)/two.tsx
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/auth/index.tsx
  apps/expo/src/app/award/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/notif/dm/index.tsx
  apps/expo/src/app/post/index.tsx
  apps/expo/src/components/auth/sign-in-w-oauth.tsx
  apps/expo/src/components/toggle/Toggle.tsx
  apps/expo/src/components/ui/bottom-sheet.tsx
  apps/expo/src/components/ui/button.tsx
  apps/expo/src/styles/colors.tsx
  apps/expo/svg.d.ts
  apps/expo/tailwind.config.ts
  apps/expo/tsconfig.json
  packages/db/package.json
  packages/ui/package.json
  packages/validators/package.json
  pnpm-lock.yaml
  tooling/eslint/package.json
  tooling/prettier/index.mjs
  tooling/prettier/package.json
  tooling/tailwind/package.json
  turbo/generators/templates/package.json.hbs
Labels: help wanted, frontend

#123 118 mock data auto generation
  .gitignore
  packages/db/src/scripts/python/README.md
  packages/db/src/scripts/python/generate.py
Labels: enhancement, back burner

#147 146 ci cd on every pull request, relief heavy burdern
  .github/issue_mock/general_issue.md
  .github/workflows/ci.yml
  .github/workflows/cov.yml
  codecov.yml
Labels: documentation, build

#114 Frontend -- Add Existing Workout Page
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/workout/startExisting/index.tsx
Labels: frontend

#159 158 bug broken lock file and time algo jest failed
  .env.example
  .github/issue_mock/general_issue.md
  .github/issue_template.md
  .github/workflows/cov.yml
  apps/expo/babel.config.js
  apps/expo/jest.config.ts
  apps/expo/metro.config.js
  apps/expo/setup-jest.js
  apps/expo/src/app/(tabs)/_layout.tsx
  apps/expo/src/app/(tabs)/one.tsx
  apps/expo/src/app/(tabs)/two.tsx
  apps/expo/src/app/__snapshots__/privacy-policy.test.tsx.snap
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/contact-us.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/privacy-policy.test.tsx
  apps/expo/src/app/privacy-policy.tsx
  apps/expo/src/components/custom-bottom-sheet-modal.tsx
  apps/expo/src/components/timeAgo/TimeAgo.test.tsx
  apps/expo/src/components/timeAgo/__snapshots__/TimeAgo.test.tsx.snap
  apps/expo/src/components/ui/bottom-sheet/__snapshots__/bottom-sheet.test.tsx.snap
  apps/expo/src/components/ui/bottom-sheet/bottom-sheet.test.tsx
  apps/expo/src/components/ui/bottom-sheet/bottom-sheet.tsx
  apps/expo/src/components/ui/button/__snapshots__/button.test.tsx.snap
  apps/expo/src/components/ui/button/button.test.tsx
  apps/expo/src/components/ui/button/button.tsx
  apps/expo/src/styles/colors.tsx
  apps/expo/src/utils/api.tsx
  apps/nextjs/package.json
  package.json
  packages/api/jest.config.ts
  packages/api/package.json
  packages/ui/package.json
  packages/validators/package.json
  pnpm-lock.yaml
  requirements.txt
  vite.config.ts
Labels: bug

#148 144 Fix name capture for misc notifs + unit tests
  .vscode/settings.json
  apps/expo/jest.config.ts
  apps/expo/src/app/_layout.tsx
  apps/expo/src/components/notif/__tests__/FriendRequestNotif.test.tsx
  apps/expo/src/components/notif/__tests__/NudgeNotif.test.tsx
  apps/expo/src/components/notif/__tests__/__snapshots__/FriendRequestNotif.test.tsx.snap
  apps/expo/src/components/notif/__tests__/__snapshots__/NudgeNotif.test.tsx.snap
  apps/expo/src/components/notif/miscNotifs/FriendRequestNotif.tsx
  apps/expo/src/components/notif/miscNotifs/NudgeNotif.tsx
  apps/expo/src/components/notif/miscNotifs/miscNotifs.tsx
  apps/expo/src/context/global-context.tsx
  packages/api/src/router/notif.ts
Labels: enhancement, build

#136 122 frontend spotify component
  .github/issue_template.md
  .github/workflows/ci.yml
  .github/workflows/cov.yml
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/spotify/index.tsx
  apps/expo/src/components/spotify/song-progress.tsx
  apps/expo/src/components/spotify/spotify.tsx
  packages/api/src/router/spotify.ts
Labels: frontend

#164 161 bug testing trpc got hands code coverage for api folder
  .editorconfig
  .github/pull_request_template.md
  .github/workflows/cov.yml
  .gitignore
  apps/expo/package.json
  apps/expo/src/app/user/index.tsx
  package.json
  packages/api/index.ts
  packages/api/jest.config.ts
  packages/api/package.json
  packages/api/src/__test__/exercise.test.ts
  packages/api/src/__test__/friend.test.ts
  packages/api/src/__test__/notif.test.ts
  packages/api/src/__test__/spotify.test.ts
  packages/api/src/__test__/user.test.ts
  packages/api/src/__test__/workout.test.ts
  packages/api/src/__tests__/notif.test.ts
  packages/api/src/__tests__/post.test.ts
  packages/api/src/context.ts
  packages/api/src/root.ts
  packages/api/src/trpc.ts
  packages/api/vite.config.ts
  packages/db/prisma/schema.prisma
  pnpm-lock.yaml
  vite.config.ts
Labels: bug, enhancement, build
