Repository UNLV-CS472-672/2024-S-GROUP3-Barbell, pull requests merged in 2024-04, with the labels that each got.

#167 85 frontend gc page
  apps/expo/src/app/messages/index.tsx
  apps/expo/src/app/notif/misc/index.tsx
  apps/expo/src/components/notif/Conversation.tsx
  apps/expo/src/components/notif/RotatingBarbellIcon.tsx
  apps/expo/src/components/notif/__tests__/RotatingBarbellIcon.test.tsx
  apps/expo/src/components/notif/__tests__/__snapshots__/RotatingBarbellIcon.test.tsx.snap
  apps/expo/src/components/notif/__tests__/__snapshots__/gcNotifs.test.tsx.snap
  apps/expo/src/components/notif/__tests__/gcNotifs.test.tsx
  apps/expo/src/components/notif/dmNotifs/Conversation.tsx
  apps/expo/src/components/notif/dmNotifs/dmNotifs.tsx
  apps/expo/src/components/notif/gcNotifs.tsx
  apps/expo/src/components/notif/gcNotifs/gcNotifs.tsx
  apps/expo/src/components/notif/miscNotifs/miscNotifs.tsx
  apps/expo/src/context/global-context.tsx
  apps/expo/src/utils/makeChatName.ts
  packages/api/src/router/notif.ts
  packages/db/prisma/schema.prisma
  packages/db/src/mock-data/notification.json
  packages/db/src/scripts/seed.ts
Labels: frontend

#169 85 frontend gc page
  apps/expo/src/components/notif/dmNotifs/dmNotifs.tsx
  apps/expo/src/components/notif/gcNotifs/gcNotifs.tsx
Labels: enhancement

#170 ReadByUserIds functionality: new API, component modification
  apps/expo/src/components/notif/Conversation.tsx
  packages/api/src/router/notif.ts
Labels: frontend, backend

#171 64 add workout view layout
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/tracker/index.tsx
  apps/expo/src/components/tracker/__snapshots__/set-entry-header.test.tsx.snap
  apps/expo/src/components/tracker/exercise-entry.test.tsx
  apps/expo/src/components/tracker/exercise-entry.tsx
  apps/expo/src/components/tracker/set-entry-header.test.tsx
  apps/expo/src/components/tracker/set-entry-header.tsx
  apps/expo/src/components/tracker/set-entry.test.tsx
  apps/expo/src/components/tracker/set-entry.tsx
  apps/expo/src/components/tracker/workout-timer.test.tsx
  apps/expo/src/components/tracker/workout-timer.tsx
  apps/expo/src/components/tracker/workout-tracker-header.test.tsx
  apps/expo/src/components/tracker/workout-tracker-header.tsx
  apps/expo/src/components/tracker/workout-tracker.test.tsx
  apps/expo/src/components/tracker/workout-tracker.tsx
  apps/expo/src/components/ui/button/button.tsx
  apps/expo/src/components/ui/custom-bottom-sheet-modal.tsx
  apps/expo/src/styles/colors.tsx
  apps/expo/src/utils/timeFormatter.test.ts
  apps/expo/src/utils/timerFormatter.ts
  apps/expo/tailwind.config.ts
Labels: frontend

#182 Update snapshots for notif and tracker components
  apps/expo/package.json
  apps/expo/src/components/notif/__tests__/__snapshots__/FriendRequestNotif.test.tsx.snap
  apps/expo/src/components/notif/__tests__/__snapshots__/NudgeNotif.test.tsx.snap
  apps/expo/src/components/tracker/__snapshots__/set-entry-header.test.tsx.snap
Labels: frontend

#172 157 account screen functionality
  apps/expo/jest.config.ts
  apps/expo/src/app/user/account-settings.tsx
  apps/expo/src/app/user/index.tsx
  apps/expo/src/styles/colors.tsx
  apps/expo/src/utils/constants.ts
  apps/expo/tailwind.config.ts
  packages/api/src/router/user.ts
  packages/db/prisma/schema.prisma
  packages/validators/src/index.ts
Labels: enhancement, frontend

#180 174 backend frontend implement clerk user id to retrive user data
  apps/expo/jest.config.ts
  apps/expo/package.json
  apps/expo/src/app/(tabs)/index.tsx
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/auth/index.tsx
  apps/expo/src/app/messages/index.tsx
  apps/expo/src/app/post/index.tsx
  apps/expo/src/components/auth/sign-in-w-google.test.tsx
  apps/expo/src/components/auth/sign-in-w-google.tsx
  apps/expo/src/components/auth/sign-in-w-oauth.tsx
  apps/expo/src/components/auth/sign-out.test.tsx
  apps/expo/src/components/auth/sign-out.tsx
  apps/expo/src/components/notif/Conversation.tsx
  apps/expo/src/components/notif/dmNotifs/dmNotifs.tsx
  apps/expo/src/components/notif/gcNotifs/gcNotifs.tsx
  apps/expo/src/components/notif/miscNotifs/miscNotifs.tsx
  apps/expo/src/components/ui/bottom-sheet/__snapshots__/bottom-sheet.test.tsx.snap
  apps/expo/src/components/ui/button/__snapshots__/button.test.tsx.snap
  apps/expo/src/components/ui/button/button.tsx
  apps/expo/src/context/global-context.tsx
  apps/expo/src/utils/usernameGenerator.test.ts
  apps/expo/src/utils/usernameGenerator.ts
  packages/api/src/router/user.ts
  packages/db/prisma/schema.prisma
  pnpm-lock.yaml
Labels: frontend, backend

#183 🐞fixed: by pass sign in on development branch
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/user/account-settings.tsx
  apps/expo/src/context/global-context.tsx
  packages/api/src/router/user.ts
  packages/db/src/mock-data/user.json
Labels: bug

#185 Friend model changes, New API, Friend Request Component changes
  apps/expo/src/app/(tabs)/index.tsx
  apps/expo/src/app/notif/misc/index.tsx
  apps/expo/src/components/notif/__tests__/FriendRequestNotif.test.tsx
  apps/expo/src/components/notif/__tests__/__snapshots__/FriendRequestNotif.test.tsx.snap
  apps/expo/src/components/notif/miscNotifs/FriendRequestNotif.tsx
  apps/expo/src/components/notif/miscNotifs/miscNotifs.tsx
  apps/expo/src/context/global-context.tsx
  packages/api/src/router/friend.ts
  packages/db/prisma/schema.prisma
  packages/db/src/mock-data/friend.json
Labels: enhancement, frontend, backend

#187 Frontend -- Search bar for filtering a list of items
  apps/expo/src/components/ui/search-bar/SearchBar.test.tsx
  apps/expo/src/components/ui/search-bar/SearchBar.tsx
Labels: enhancement, frontend

#184 152 backed api endpoints for workout collection and bugs
  packages/api/src/router/workout.ts
  packages/db/prisma/schema.prisma
  packages/db/src/mock-data/exercise.json
  packages/db/src/mock-data/workoutLog.json
  packages/db/src/scripts/seed.ts
Labels: bug, backend

#200 Bugs -- versions conflict after merging
  apps/expo/package.json
  pnpm-lock.yaml
Labels: bug

#201 190 frontend start existing workout functionality
  apps/expo/src/app/workout/createNew/index.tsx
  apps/expo/src/app/workout/startExisting/index.tsx
  apps/expo/src/components/ui/search-bar/SearchBar.tsx
  apps/expo/src/components/workout/exerciseList.tsx
  apps/expo/src/components/workout/workoutList.tsx
Labels: frontend

#204 177 frontend add testing to notifs
  apps/expo/jest.config.ts
  apps/expo/src/__mocks__/@prisma/client.ts
  apps/expo/src/__tests__/__snapshots__/NudgeNotif.test.tsx.snap
  apps/expo/src/components/notif/dmNotifs/dmNotifs.test.tsx
  apps/expo/src/components/notif/dmNotifs/dmNotifs.tsx
  apps/expo/src/components/notif/miscNotifs/NudgeNotif.tsx
Labels: frontend

#203 194 frontend post dashboard component
  apps/expo/src/components/notif/RotatingBarbellIcon.tsx
  apps/expo/src/components/notif/dmNotifs/dmNotifs.test.tsx
  apps/expo/src/components/post/PostDashboard.test.tsx
  apps/expo/src/components/post/PostDashboard.tsx
  apps/expo/src/components/ui/label/Label.test.tsx
  apps/expo/src/components/ui/label/Label.tsx
  apps/expo/src/components/ui/label/__snapshots__/Label.test.tsx.snap
  packages/api/src/router/post.router.ts
  packages/db/prisma/schema.prisma
Labels: enhancement, frontend, backend

#212 deleted unused notif files
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/notif/dm/index.tsx
  apps/expo/src/app/notif/index.tsx
Labels: enhancement

#209 192 / Activity feed
  .gitignore
  apps/expo/src/app/activity/feed.tsx
  apps/expo/src/app/activity/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/utils/constants.ts
  packages/api/src/router/friend.router.ts
  packages/api/src/router/user.router.ts
  packages/api/src/router/workout.router.ts
  packages/db/package.json
  packages/db/src/mock-data/exercise.json
  packages/db/src/mock-data/friend.json
  packages/db/src/mock-data/user.json
  packages/db/src/mock-data/workout.json
  packages/db/src/scripts/seed.ts
  pnpm-lock.yaml
Labels: frontend, backend, build

#217 216 frontend modular nav bar
  apps/expo/src/app/notif/index.tsx
  apps/expo/src/components/ui/nav-bar/NavBar.test.tsx
  apps/expo/src/components/ui/nav-bar/NavBar.tsx
Labels: enhancement, frontend

#213 189 / refactor hard coded keypad numpad elements.
  apps/expo/src/components/ui/keypad/Keypad.tsx
Labels: enhancement

#205 189 frontend custom keyboard numeric only
  apps/expo/src/app/keypadDemo/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/components/ui/keypad/Keypad.test.tsx
  apps/expo/src/components/ui/keypad/Keypad.tsx
Labels: enhancement, frontend

#208 Frontend -- Addressing Minor Issues with MessageView
  apps/expo/package.json
  apps/expo/src/app/messages/index.tsx
  apps/expo/src/components/message/messageInput.tsx
  apps/expo/src/context/global-context.tsx
  packages/db/prisma/schema.prisma
  packages/db/src/mock-data/message.json
  pnpm-lock.yaml
Labels: bug, help wanted

#214 156 spotify generating refresh tokens
  README.md
  apps/expo/.env.example
  apps/expo/app.config.ts
  apps/expo/package.json
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/spotify/index.tsx
  apps/expo/src/components/auth/sign-out.tsx
  apps/expo/src/components/spotify/sign-in-spotify.tsx
  apps/expo/src/components/spotify/sign-out-spotify.tsx
  apps/expo/src/components/spotify/spotify.tsx
  apps/expo/src/components/spotify/spotifyToken.tsx
  apps/expo/src/hooks/useUpdateSpotify.tsx
  apps/expo/src/utils/constants.ts
  apps/nextjs/src/env.mjs
  packages/api/src/router/spotify.router.ts
  pnpm-lock.yaml
Labels: enhancement, frontend, backend

#218 207 mixed add gender to body diagram dynamically resize the body
  apps/expo/src/__tests__/FrontBackSwitch.test.tsx
  apps/expo/src/__tests__/GenderSwitch.test.tsx
  apps/expo/src/app/muscleGroup/index.tsx
  apps/expo/src/components/muscleGroup/GenderSwitch.tsx
  apps/expo/src/components/muscleGroup/__snapshots__/FrontBackSwitch.test.tsx.snap
  apps/expo/src/context/global-context.tsx
  packages/db/prisma/schema.prisma
Labels: enhancement, backend

#222 221 / Lookup WorkoutLogs instead of Workout for completed workouts
  apps/expo/src/app/activity/feed.tsx
  apps/expo/src/app/activity/index.tsx
  packages/api/src/router/workout.router.ts
  packages/db/src/mock-data/workout.json
  packages/db/src/mock-data/workoutLog.json
Labels: bug, backend

#223 173 / Update createNew and startExisting workout pages
  apps/expo/src/app/workout/createNew/index.tsx
  apps/expo/src/app/workout/startExisting/index.tsx
  apps/expo/src/components/workout/exerciseList.tsx
  apps/expo/src/components/workout/workoutList.tsx
Labels: enhancement, frontend

#238 224 frontend unselect muscle improve musclegroup page add more exercises
  apps/expo/src/app/muscleGroup/index.tsx
  packages/db/src/mock-data/exercise.json
Labels: enhancement, backend

#237 193 / frontend recent posts
  apps/expo/src/app/activity/feed.tsx
  apps/expo/src/app/activity/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/post/feed.tsx
  apps/expo/src/app/post/new.tsx
  apps/expo/src/app/post/post.tsx
  apps/expo/src/components/post/new.test.tsx
  apps/expo/src/components/post/post.test.tsx
  apps/expo/src/utils/constants.ts
  apps/nextjs/src/app/_components/posts.tsx
  packages/api/src/__tests__/post.router.test.ts
  packages/api/src/router/post.router.ts
  packages/db/prisma/schema.prisma
  packages/db/src/mock-data/post.json
  packages/db/src/scripts/python/generate.py
Labels: frontend, backend

#240 210 backend trpc websocket integration websocket go brrr brrr
  .vscode/settings.json
  README.md
  apps/expo/jest.config.ts
  apps/expo/package.json
  apps/expo/src/__mocks__/svgMock.tsx
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/messages/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/post2/index.tsx
  apps/expo/src/components/auth/sign-in-w-google.tsx
  apps/expo/src/context/global-context.tsx
  apps/expo/src/utils/trpc/api.tsx
  apps/nextjs/package.json
  apps/nextjs/src/app/_components/posts.tsx
  apps/nextjs/src/app/_components/users.tsx
  apps/nextjs/src/app/api/trpc/[trpc]/route.ts
  apps/nextjs/src/app/layout.tsx
  apps/nextjs/src/app/middleware.ts
  apps/nextjs/src/app/page.tsx
  apps/nextjs/src/app/post2/page.tsx
  apps/nextjs/src/app/providers.tsx
  apps/nextjs/src/server/ws-dev-server.ts
  apps/nextjs/src/server/ws-prod-server.ts
  apps/nextjs/src/utils/api.ts
  apps/nextjs/src/utils/trpc/api.tsx
  apps/nextjs/tsconfig.server.json
  package.json
  packages/api/index.ts
  packages/api/package.json
  packages/api/src/__test__/exercise.test.ts
  packages/api/src/__test__/friend.test.ts
  packages/api/src/__test__/notif.test.ts
  packages/api/src/__test__/spotify.test.ts
  packages/api/src/__test__/workout.test.ts
  packages/api/src/__tests__/post.router.test.ts
  packages/api/src/__tests__/user.router.test.ts
  packages/api/src/__tests__/user.test.ts
  packages/api/src/root.ts
  packages/api/src/router/post.router.ts
  packages/api/src/router/post2.router.ts
  packages/api/src/trpc.ts
  packages/db/package.json
  packages/db/prisma/migrations/20240423012222_i_need_to_strangle_someone_part_2_post_is_evil/migration.sql
  packages/db/prisma/schema.prisma
  packages/db/src/new-gen-data/post.json
  pnpm-lock.yaml
Labels: backend, build

#228 Tracker functionality
  apps/expo/jest.config.ts
  apps/expo/package.json
  apps/expo/src/__tests__/__snapshots__/toggle.test.tsx.snap
  apps/expo/src/__tests__/tracker/exercise-entry.test.tsx
  apps/expo/src/__tests__/tracker/set-entry.test.tsx
  apps/expo/src/__tests__/tracker/workout-timer.test.tsx
  apps/expo/src/__tests__/tracker/workout-tracker-header.test.tsx
  apps/expo/src/__tests__/tracker/workout-tracker.test.tsx
  apps/expo/src/__tests__/ui/picker-modal/__snapshots__/picker-modal.test.tsx.snap
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/tracker/index.tsx
  apps/expo/src/app/workout-completion/_layout.tsx
  apps/expo/src/app/workout-completion/index.tsx
  apps/expo/src/components/notif/RotatingBarbellIcon.tsx
  apps/expo/src/components/toggle/toggle.tsx
  apps/expo/src/components/tracker/exercise-entry.tsx
  apps/expo/src/components/tracker/set-entry.tsx
  apps/expo/src/components/tracker/set-type-button.tsx
  apps/expo/src/components/tracker/workout-timer.tsx
  apps/expo/src/components/tracker/workout-tracker-header.tsx
  apps/expo/src/components/tracker/workout-tracker.tsx
  apps/expo/src/components/ui/picker-modal/picker-modal.style.ts
  apps/expo/src/components/ui/picker-modal/picker-modal.tsx
  apps/expo/src/utils/timerFormatter.ts
  apps/expo/src/utils/workout-tracker-utils.ts
  packages/api/src/root.ts
  packages/api/src/router/user.router.ts
  packages/api/src/router/workout-log.router.ts
  packages/api/src/router/workout-template.router.ts
  packages/api/tsconfig.json
  packages/db/prisma/schema.prisma
  packages/db/src/mock-data/exercise.json
  packages/db/src/mock-data/set.json
  packages/db/src/mock-data/workout.json
  packages/db/src/mock-data/workoutLog.json
  packages/db/src/mock-data/workoutTemplate.json
  packages/db/src/scripts/seed.ts
  packages/validators/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, frontend, backend

#241 Frontend - Rest Timer for Workout Tracker
  apps/expo/package.json
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/rest-timer/index.tsx
  pnpm-lock.yaml
Labels: enhancement, frontend

#232 New post and post feed
  apps/expo/jest.config.ts
  apps/expo/src/app/(dashboard)/_layout.tsx
  apps/expo/src/app/(dashboard)/unused.tsx
  apps/expo/src/app/activity/feed.tsx
  apps/expo/src/app/activity/index.tsx
  apps/expo/src/app/award/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/post/feed.tsx
  apps/expo/src/app/post/new.tsx
  apps/expo/src/app/post/post.tsx
  apps/expo/src/components/post/new.test.tsx
  apps/expo/src/components/post/post.test.tsx
  apps/expo/src/utils/constants.ts
  apps/nextjs/src/app/_components/posts.tsx
  packages/api/src/__tests__/post.router.test.ts
  packages/api/src/router/friend.router.ts
  packages/api/src/router/post.router.ts
  packages/db/prisma/schema.prisma
  packages/db/src/mock-data/post.json
  packages/db/src/scripts/python/generate.py
Labels: frontend, backend

#248 add contributions.py and mined github data for DP3 charts & graphs.
  scripts/contributions.py
  scripts/json/dp3/comments.json
  scripts/json/dp3/issues.json
  scripts/json/dp3/pulls.json
  scripts/json/dp3/reviews.json
Labels: enhancement

#251 Bugs -- ci cd trpc vercel render incident
  .github/workflows/cov.yml
  apps/nextjs/src/utils/trpc/api.tsx
  package.json
Labels: bug

#253 🐧bugs: hot fixed
  apps/expo/package.json
  apps/expo/src/utils/trpc/api.tsx
  apps/nextjs/package.json
  apps/nextjs/src/utils/trpc/api.tsx
  packages/validators/index.tsx
  pnpm-lock.yaml
Labels: bug

#255 249 frontend navbar style changes
  apps/expo/src/components/ui/nav-bar/NavBar.tsx
Labels: enhancement, frontend

#225 153 frontend privacy policy screen
  .vscode/settings.json
  apps/expo/src/__tests__/__snapshots__/privacy-policy.test.tsx.snap
  apps/expo/src/__tests__/privacy-policy.test.tsx
  apps/expo/src/app/(dashboard)/account-settings.tsx
  apps/expo/src/app/privacy-policy/index.tsx
Labels: frontend

#229 Frontend - Contact Us Screen
  apps/expo/src/app/contact-us/index.tsx
Labels: enhancement, frontend

#262 Profile view page + other styling enhancements
  apps/expo/src/__tests__/ui/__snapshots__/SearchBar.test.tsx.snap
  apps/expo/src/app/(dashboard)/index.tsx
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/frlist/index.tsx
  apps/expo/src/app/messages/index.tsx
  apps/expo/src/app/notif/index.tsx
  apps/expo/src/app/privacy-policy/index.tsx
  apps/expo/src/app/profile/index.tsx
  apps/expo/src/components/frlist/Friend.tsx
  apps/expo/src/components/profile/FriendStatus.tsx
  apps/expo/src/components/profile/HeaderElement.tsx
  apps/expo/src/components/profile/IncomingFriendAlert.tsx
  apps/expo/src/components/profile/MessageButton.tsx
  apps/expo/src/components/profile/ProfilePosts.tsx
  apps/expo/src/components/profile/ProfileWorkouts.tsx
  apps/expo/src/components/profile/ViewSwitcher.tsx
  apps/expo/src/components/ui/nav-bar/BarbellTitle.tsx
  apps/expo/src/components/ui/search-bar/SearchBar.tsx
  packages/api/src/router/post.router.ts
  packages/api/src/router/user.router.ts
  packages/db/src/scripts/seed.ts
Labels: enhancement, frontend, backend

#259 xxx -- dp3 data mining pt 2
  .gitignore
  scripts/contributions.py
  scripts/json/dp3/.keep
  scripts/json/dp3/comments.json
  scripts/json/dp3/issues.json
  scripts/json/dp3/pulls.json
  scripts/json/dp3/reviews.json
Labels: enhancement

#264 Restyle app
  apps/expo/src/app/(dashboard)/_layout.tsx
  apps/expo/src/app/(dashboard)/account-settings.tsx
  apps/expo/src/app/(dashboard)/create-new-workout.tsx
  apps/expo/src/app/(dashboard)/index.tsx
  apps/expo/src/app/(dashboard)/start-saved-workout.tsx
  apps/expo/src/app/(workout)/_layout.tsx
  apps/expo/src/app/(workout)/index.tsx
  apps/expo/src/app/_layout.tsx
  apps/expo/src/app/activity/feed.tsx
  apps/expo/src/app/auth/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/app/rest-timer/index.tsx
  apps/expo/src/app/user/achievements.tsx
  apps/expo/src/app/user/activity-history.tsx
  apps/expo/src/app/user/personal-data.tsx
  apps/expo/src/app/user/workout-progress.tsx
  apps/expo/src/components/auth/sign-in-w-google.tsx
  apps/expo/src/components/auth/sign-out.tsx
  apps/expo/src/components/feed/activity.tsx
  apps/expo/src/components/post/PostDashboard.tsx
  apps/expo/src/components/tracker/rest-timer.tsx
  apps/expo/src/components/ui/nav-bar/NavBar.tsx
  apps/expo/src/components/ui/picker-modal/picker-modal.tsx
  apps/expo/src/components/ui/search-bar/SearchBar.tsx
  apps/expo/src/components/ui/under-dev-tag.tsx
  apps/expo/src/components/workout/exerciseList.tsx
  apps/expo/src/components/workout/sortByEquipment.tsx
  apps/expo/src/components/workout/workoutList.tsx
  apps/expo/src/context/global-context.tsx
  apps/expo/src/styles/colors.tsx
  packages/api/src/router/friend.router.ts
  packages/api/src/router/user.router.ts
  packages/db/src/mock-data/workoutTemplate.json
  packages/db/src/scripts/seed.ts
Labels: frontend, backend

#266 implement functionality for button to remove person as a friend
  apps/expo/src/app/profile/index.tsx
  apps/expo/src/components/profile/FriendStatus.tsx
  packages/api/src/router/friend.router.ts
Labels: frontend, backend

#256 195 frontend workout frequency chart 1
  apps/expo/package.json
  apps/expo/src/app/(dashboard)/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/components/workout/frequency_graph.tsx
  packages/db/src/scripts/seed.ts
  pnpm-lock.yaml
Labels: frontend

#258 239 frontend new select exercise based on muscle group page
  apps/expo/src/app/(dashboard)/_layout.tsx
  apps/expo/src/app/filteredExercises/index.tsx
  apps/expo/src/app/muscleGroup/index.tsx
  apps/expo/src/app/nav/index.tsx
  apps/expo/src/components/ui/nav-bar/NavBar.tsx
  apps/expo/src/components/workout/exerciseList.tsx
  apps/expo/src/components/workout/sortByEquipment.tsx
Labels: frontend

#269 267 frontend redesign friend activity page
  apps/expo/src/app/(dashboard)/index.tsx
  apps/expo/src/app/activity/feed.tsx
  apps/expo/src/components/post/PostDashboard.tsx
  apps/expo/src/utils/constants.ts
Labels: frontend

#268 Xxx cover
  apps/expo/src/__tests__/ui/barbell-title.test.tsx
  apps/expo/src/__tests__/ui/under-dev-tag.test.tsx
  apps/expo/src/components/ui/nav-bar/BarbellTitle.tsx
  apps/expo/src/components/ui/under-dev-tag.tsx
  packages/api/src/__tests__/friend.router.test.ts
  packages/api/src/__tests__/user.router.test.ts
  packages/api/src/router/friend.router.ts
  packages/api/src/router/user.router.ts
Labels: build

#271 Pls pls pls
  apps/expo/package.json
  apps/expo/src/__tests__/util/constants.test.ts
  apps/expo/src/components/notif/miscNotifs/NudgeNotif.tsx
  apps/expo/src/utils/trpc/api.tsx
  apps/nextjs/src/utils/trpc/api.tsx
  pnpm-lock.yaml
Labels: build

#273 Message functionality for demo
  apps/expo/src/app/messages/index.tsx
  apps/expo/src/components/message/messageInput.tsx
Labels: bug
